name: CI/CD Pipeline for EKS

on:
  push:
    branches:
      - main  # Cambia a la rama que usas para desplegar si es diferente.

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      CLUSTER_NAME: "demo-cluster"  # Cambia al nombre real de tu clúster.
      DOCKER_IMAGE: "mariomtk8/front_term1"  # Imagen del backend.
      DOCKER_TAG: "v2"

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
        docker push $DOCKER_IMAGE:$DOCKER_TAG

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME

    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/dotnetapi dotnet-core-and-mssql-app=$DOCKER_IMAGE:$DOCKER_TAG
        kubectl rollout restart deployment/dotnetapi
